name: gerador_de_apostas
description: Um gerador de apostas para a Mega Sena.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Para BLoC (gerência de estado)
  flutter_bloc: ^8.1.3

  # Para Modular (injeção de dependência e rotas)
  flutter_modular: ^6.3.2

  # Para comparação de objetos (usado pelo BLoC)
  equatable: ^2.0.5

  # Ícones
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

# Adicione esta seção no final do arquivo pubspec.yaml
flutter_launcher_icons:
  android: "launcher_icon" # Nome do ícone para Android
  ios: true                # Gerar ícones para iOS
  image_path: "assets/icon.png" # Caminho para a sua imagem
  min_sdk_android: 21      # Opcional: versão mínima do Android